services:
  lunatv-enhanced-core-fnos:
    image: ghcr.nju.edu.cn/szemeng76/lunatv:latest
    container_name: lunatv-enhanced-core-fnos
    restart: always
    ports:
      - '22391:3000'
    environment:
      - USERNAME=${wizard_username:-admin}
      - PASSWORD=${wizard_password:-admin_password}
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://lunatv-enhanced-kvrocks-fnos:6666
      - NEXT_PUBLIC_SITE_NAME=LunaTV Enhanced
    networks:
      - lunatv-network
    depends_on:
      lunatv-enhanced-kvrocks-fnos:
        condition: service_started
  lunatv-enhanced-kvrocks-fnos:
    image: apache/kvrocks
    container_name: lunatv-enhanced-kvrocks-fnos
    restart: always
    volumes:
      - lunatv-enhanced-data-fnos:/var/lib/kvrocks
    networks:
      - lunatv-network

networks:
  lunatv-network:
    driver: bridge

volumes:
  lunatv-enhanced-data-fnos:
